sudo: true
language: java

jdk:
  - "oraclejdk8"

node_js:
  - "5.11"

before_install:
  - npm i -g "serverless@1.2.1"

install: true

script:
  - ./gradlew clean build
  - serverless deploy --stage dev