sudo: true

language: java

jdk:
  - "oraclejdk8"

before_install:
  - nvm install 4.2
  - npm i -g "serverless@1.17.0"

install: true

script:
  - ./gradlew clean build
#  - serverless deploy --stage dev

