service: serverless-java-template

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-west-1

package:
  artifact: build/distributions/information.zip

functions:
  informations:
    handler: com.happysathya.handler.InformationHandler
    events:
      - http:
          path: api/info
          method: get
